# Generated by Django 2.2.19 on 2022-02-23 07:26

from django.db import migrations, models
import django.db.models.deletion
import django_mysql.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('panel', '0206_modelconnection_time_per_frame'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnotationDataset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('version', models.CharField(default='latest', max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('model_type', models.CharField(choices=[('d', 'DETECTOR'), ('c', 'CLASSIFIER'), ('s', 'SEGMENTATION')], max_length=5)),
                ('config', django_mysql.models.JSONField(default=dict)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='Frame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='annotation/')),
                ('annotated', models.BooleanField(default=False)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='annotation.AnnotationDataset')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='Segmentation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('annotated_by', models.CharField(choices=[('p', 'PERSON'), ('m', 'MODEL')], default='p', max_length=5)),
                ('label_class', models.PositiveSmallIntegerField()),
                ('frame_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segmentation_data', to='annotation.Frame')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('x', models.DecimalField(decimal_places=20, max_digits=50)),
                ('y', models.DecimalField(decimal_places=20, max_digits=50)),
                ('segment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segmentation_coords', to='annotation.Segmentation')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Detector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('x', models.DecimalField(decimal_places=20, max_digits=50)),
                ('y', models.DecimalField(decimal_places=20, max_digits=50)),
                ('w', models.DecimalField(decimal_places=20, max_digits=50)),
                ('h', models.DecimalField(decimal_places=20, max_digits=50)),
                ('annotated_by', models.CharField(choices=[('p', 'PERSON'), ('m', 'MODEL')], default='p', max_length=5)),
                ('label_class', models.PositiveSmallIntegerField()),
                ('frame_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detector_data', to='annotation.Frame')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='DeploymentHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=500)),
                ('total_data', models.IntegerField(default=0)),
                ('batch_size', models.PositiveSmallIntegerField()),
                ('epochs', models.PositiveSmallIntegerField()),
                ('img_size', models.PositiveSmallIntegerField()),
                ('meta_data', models.TextField()),
                ('status', models.CharField(choices=[('training', 'training'), ('trained', 'trained'), ('failed', 'failed')], default='failed', max_length=30)),
                ('is_active', models.BooleanField(default=False)),
                ('is_deployed', models.BooleanField(default=False)),
                ('dataset', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='annotation.AnnotationDataset')),
                ('model', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='panel.ModelConnection')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='Classifier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('annotated_by', models.CharField(choices=[('p', 'PERSON'), ('m', 'MODEL')], default='p', max_length=5)),
                ('label_class', models.PositiveSmallIntegerField()),
                ('frame_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classifier_data', to='annotation.Frame')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
